# Generated by Django 4.1.5 on 2023-01-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('balls_count', models.IntegerField(verbose_name='Balls')),
                ('middled_count', models.IntegerField(verbose_name='Middled')),
                ('edged_count', models.IntegerField(verbose_name='Edged')),
            ],
        ),
    ]
