# Generated by Django 4.1.5 on 2023-01-31 17:56

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('react_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='missed_count',
            field=models.IntegerField(default=0, verbose_name='Missed'),
            preserve_default=False,
        ),
    ]
