# Generated by Django 4.1.5 on 2023-02-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('react_backend', '0002_player_missed_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='middled_count',
        ),
    ]
